In [8]:
import numpy

In [9]:
from matplotlib import pyplot

In [10]:
%matplotlib inline

In [11]:
T = 50.0

In [12]:
dt = 0.1

In [13]:
N = int(T/dt) + 1

In [14]:
print (N)

501


In [15]:
t = numpy.arange(0.0,T+dt,dt)

In [16]:
print(t)

[  0.    0.1   0.2   0.3   0.4   0.5   0.6   0.7   0.8   0.9   1.    1.1
   1.2   1.3   1.4   1.5   1.6   1.7   1.8   1.9   2.    2.1   2.2   2.3
   2.4   2.5   2.6   2.7   2.8   2.9   3.    3.1   3.2   3.3   3.4   3.5
   3.6   3.7   3.8   3.9   4.    4.1   4.2   4.3   4.4   4.5   4.6   4.7
   4.8   4.9   5.    5.1   5.2   5.3   5.4   5.5   5.6   5.7   5.8   5.9
   6.    6.1   6.2   6.3   6.4   6.5   6.6   6.7   6.8   6.9   7.    7.1
   7.2   7.3   7.4   7.5   7.6   7.7   7.8   7.9   8.    8.1   8.2   8.3
   8.4   8.5   8.6   8.7   8.8   8.9   9.    9.1   9.2   9.3   9.4   9.5
   9.6   9.7   9.8   9.9  10.   10.1  10.2  10.3  10.4  10.5  10.6  10.7
  10.8  10.9  11.   11.1  11.2  11.3  11.4  11.5  11.6  11.7  11.8  11.9
  12.   12.1  12.2  12.3  12.4  12.5  12.6  12.7  12.8  12.9  13.   13.1
  13.2  13.3  13.4  13.5  13.6  13.7  13.8  13.9  14.   14.1  14.2  14.3
  14.4  14.5  14.6  14.7  14.8  14.9  15.   15.1  15.2  15.3  15.4  15.5
  15.6  15.7  15.8  15.9  16.   16.1  16.2  16.3  1

In [17]:
h0 = 0.0

In [18]:
v0 = 0.0

In [19]:
g = 9.81

In [20]:
m_dot_p = 20.0

In [21]:
m_p_nol = 100.0

In [22]:
v_e = 325.0

In [23]:
rho = 1.091

In [24]:
r = 0.5

In [25]:
A = (22/7)*(r**2)

In [26]:
print(r**2)

0.25


In [27]:
C_D = 0.15

In [28]:
m_s = 50.0

In [29]:
print(t[0])

0.0


In [30]:
acceleration = 0.0

In [31]:
clear(output)

In [32]:
output = numpy.array([t[0],h0,v0,m_p_nol,acceleration])

In [33]:
h = numpy.zeros(N)

In [34]:
h[0] = h0

In [39]:
for n in range (1,N):
    print (output)
    kec_1 = output[2]
    
    if n < 51 :
        m_p = m_p_nol - 20.0 * t[n-1]
        komponen_v = - g + (m_dot_p*v_e-0.5*rho*output[2]*abs(output[2])*A*C_D)/(m_s+m_p)
    else :
        m_p=0
        komponen_v=-g+(-0.5*rho*output[2]*abs(output[2])*A*C_D)/m_s
        
    v = output[2]+dt*komponen_v
    
    acceleration = (v-output[2])/dt # acceleration = komponen_v
    
    output = output + numpy.array([dt, dt*output[2], - output[2]+v, -output[3]+m_p, - output[4]+acceleration])
    
    h[n]=output[1]

[   0.    0.    0.  100.    0.]
[   0.1           0.            3.35233333  100.           33.52333333]
[  0.2          0.33523333   6.76273704  98.          34.10403708]
[  0.3          1.01150704  10.23177791  96.          34.69040872]
[  0.4          2.03468483  13.75999278  94.          35.28214871]
[  0.5          3.41068411  17.34788525  92.          35.87892462]
[  0.6          5.14547263  20.99592214  90.          36.48036899]
[  0.7          7.24506485  24.70452986  88.          37.08607716]
[  0.8          9.71551783  28.47409035  86.          37.69560494]
[  0.9         12.56292687  32.30493698  84.          38.30846629]
[  1.          15.79342057  36.19735006  82.          38.92413077]
[  1.1         19.41315557  40.15155217  80.          39.5420211 ]
[  1.2         23.42831079  44.16770321  78.          40.16151041]
[  1.3         27.84508111  48.24589518  76.          40.78191966]
[  1.4         32.66967063  52.38614666  74.          41.40251478]
[  1.5         37.9082852